Local k8s cluster created and service deployed
CSCI-GA-2820-FA23-001/recommendations pull request #52
Opened 2023-11-28 05:14 UTC by sidoodler

Created a local k8s cluster and deployed the service to it.

2023-11-28 21:52 UTC, WYB929 requested changes
Please add Dockerfile in the root dictionary so that our app could run properly.  Thanks.

2023-11-29 01:02 UTC, WYB929 approved these changes

2023-11-29 02:33 UTC, oyster14 reviewed
Hi,

I made changes on this code, and tested our code on the local cluster.

2023-11-29 03:00 UTC, WYB929 approved these changes
Great job! App is deployed on the local cluster successfully.

2023-11-29 03:01 UTC, merged